### ISSUE TITLE
Docker-composeができません。

### ISSUE THREAD

**Issue by phys-ken** [Kokensha/book-ml#2]
P.267にあるDocker-composeができません。以下のように、cv2がインポートできないようです。
↓以下の記事も参考にdockerfileを書き換えたりもしてみましたが、うまくできませんでした。
https://qiita.com/narista/items/a3d7d26ae50d54c2553a

Dockerに詳しくないので、どう解決すれば良いかがわかりません。よろしければ解決策を、自己解決するためにはどのように学習をすれば良いのかを、教えてください。

（ドキュメント）docker-python3-flask-ml-app % docker-compose up
Creating network "docker-python3-flask-ml-app_default" with the default driver
Creating docker-python3-flask-ml-app_server_1 ... done
Attaching to docker-python3-flask-ml-app_server_1
server_1  | Traceback (most recent call last):
server_1  |   File "app.py", line 14, in <module>
server_1  |     import cv2
server_1  |   File "/usr/local/lib/python3.5/site-packages/cv2/__init__.py", line 5, in <module>
server_1  |     from .cv2 import *
server_1  | ImportError: libGL.so.1: cannot open shared object file: No such file or directory
docker-python3-flask-ml-app_server_1 exited with code 1

**Comment by kawashimaken** [comment]
お返事が遅くなってすみません。
下記のrepoをご利用いただけます。
https://github.com/kawashimaken/docker-python3-flask-ml-app

このrepoは書籍と一致することが優先しており、あんまり大胆にバージョンアップできないため
dockerの部分を切り出して、別（上の）のrepoを作りました。
そちらは書籍と関係ありませんので、随時必要な更新をしていこうと思っています。
お手数をおかけします。
また、解決方法ですが
dockerイメージになかった外部パッケージがあるみたいで、dockerfileに下記の１行を追加することで解決しました。

`RUN apt-get update && apt-get install -y libgl1-mesa-glx`

上のrepoのcommit履歴で確認できます。
引き続きよろしくお願い致します。
`docker-compose build
docker-compose up`
で実行できるかと思います。

**Comment by kawashimaken** [comment]
本件、一旦クローズさせていただきます。
また、ご不明点等がありましたら、随時お気軽にコメントしてください。よろしくお願いします。
