### ISSUE TITLE
'.gitignore ' ファイル名の最後の空白について

### ISSUE THREAD

**Issue by ganaware** [Kokensha/book-ml#3]
https://github.com/Kokensha/book-ml/blob/master/.gitignore%20

.gitignore ファイルについてですが、ファイル名の最後に空白が入っているためチェックアウトに失敗することがあります。
具体的には以下のようになりました。
- Windows10 + git for windows ... 失敗
- Linux (Ubuntu) ... 成功

ファイル名の最後の空白の除去をお願いします。

**Comment by kawashimaken** [comment]
ご指摘ありがとうございます！
ファイル名の最後の空白を除去して、masterにpushしました。
https://github.com/Kokensha/book-ml/commits/master

本件一旦クローズします。
また何かがありましたら、いつでもお気軽にご連絡ください。
